{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "cellhive.labels" . | nindent 4 }}
type: Opaque
stringData:
  CELLHIVE_ROOT_KEY: {{ required "set rootKey or existingSecret (openssl rand -base64 32)" .Values.rootKey | quote }}
  {{- if .Values.config.awsEndpoint }}
  AWS_ENDPOINT_URL: {{ .Values.config.awsEndpoint | quote }}
  AWS_REGION: {{ .Values.config.awsRegion | default "us-east-1" | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.config.awsAccessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.config.awsSecretKey | quote }}
  {{- end }}
{{- end }}
