// Package doruntime renders and launches the do-runtime workerd process
// (docs/durable-objects.md): a native Durable Object host actor that runs tenant
// Durable Objects as facets with local-disk SQLite storage (ADR-077).
package doruntime

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"

	"cellhive/internal/workerdbin"
)

// outboundCategories are the workerd network categories a tenant outbound policy
// may name.
var outboundCategories = map[string]bool{"public": true, "private": true, "local": true}

// OutboundAllowList renders the tenant facet outbound policy for the capnp
// config. Empty defaults to "public" (ADR-130).
func (c Config) OutboundAllowList() string {
	if len(c.OutboundAllow) == 0 {
		return `"public"`
	}
	parts := make([]string, 0, len(c.OutboundAllow))
	for _, a := range c.OutboundAllow {
		parts = append(parts, strconv.Quote(strings.TrimSpace(a)))
	}
	return strings.Join(parts, ", ")
}

// WsAllowList renders the facet DO-WebSocket binding's network policy (the
// tenant-visible CH_DO_CONNECT binding). Empty falls back to public+private
// for back-compat; production narrows it to the runtime cluster's addresses.
func (c Config) WsAllowList() string {
	parts := make([]string, 0, len(c.WsAllow))
	for _, a := range c.WsAllow {
		if a = strings.TrimSpace(a); a != "" {
			parts = append(parts, strconv.Quote(a))
		}
	}
	if len(parts) == 0 {
		return `"public", "private"`
	}
	return strings.Join(parts, ", ")
}

// Config configures one do-runtime instance.
type Config struct {
	// CellURL/CellToken are the cell-agent base URL and internal-role token
	// (used to fetch tenant bundles and to authenticate /v1/do/invoke).
	CellURL   string
	CellToken string
	// Addr is the workerd HTTP listen address, e.g. "*:8788".
	Addr string
	// DiskDir holds the per-class Durable Object SQLite storage.
	DiskDir string
	// PlatformJS is the directory holding host.js.
	PlatformJS string
	// FacadesJS is the path to facades.js (tenant binding facades). When empty,
	// it is derived from PlatformJS (../platform/facades.js).
	FacadesJS string
	// AIURL/AIKey configure the BYO OpenAI-compatible AI binding endpoint.
	AIURL string
	AIKey string
	// LogToken authorizes the bounded log-ingest endpoint (loaded workers).
	LogToken string
	// DoTicketSecret verifies short-lived DO owner tickets (ADR-105). Empty
	// disables ticket auth (internal token only).
	DoTicketSecret string
	// DoLeaseS is the DO owner lease TTL in seconds (empty = runtime default 30).
	// Longer reduces renew churn; shorter fails over faster.
	DoLeaseS string
	// WsAllow is the network policy for the tenant-visible CH_DO_CONNECT binding
	// (DO WebSocket upgrades only). Empty falls back to public+private.
	WsAllow []string
	// OutboundAllow is the tenant DO facets' outbound network policy (ADR-130).
	// Empty = ["public"]. Facets may reach the allowed ranges via
	// `cloudflare:sockets connect()`; a Durable Object can hold the socket across
	// requests, which is how tenant code pools connections locally.
	OutboundAllow []string
	// DOObjectIndex mirrors the runtime object registry into the bucket so a cold
	// start can enumerate objects without asking every runtime (ADR-108).
	DOObjectIndex bool
	// NodeID/Advertise identify this do-runtime task in owner records.
	NodeID    string
	Advertise string
	// PreventEviction selects the resident (true) or evictable (false) host
	// actor configuration (ADR-078). Default is resident.
	PreventEviction bool
	// GateURL is the do-supervisor base URL; when set, responses are gated on
	// capture durability (ADR-083). Empty disables the gate.
	GateURL string
}

const capnpTemplate = `# Generated by do-runtime; do not edit.
using Workerd = import "/workerd/workerd.capnp";

const config :Workerd.Config = (
  services = [
    (name = "do", worker = (
      modules = [
        (name = "host.js", esModule = embed "host.js"),
        (name = "bindings.js", esModule = embed "bindings.js"),
        (name = "rpc-codec.js", esModule = embed "rpc-codec.js"),
        (name = "facades.js", esModule = embed "facades.js"),
        (name = "telemetry.js", esModule = embed "telemetry.js"),
      ],
      compatibilityDate = "2026-06-15",
      bindings = [
        (name = "LOADER", workerLoader = (id = "cellhive-do-runtime")),
        (name = "HOST", durableObjectNamespace = "Host"),
        (name = "CELL_URL", text = "{{.CellURL}}"),
        (name = "CELL_TOKEN", text = "{{.CellToken}}"),
        (name = "NODE_ID", text = "{{.NodeID}}"),
        (name = "ADVERTISE", text = "{{.Advertise}}"),
        (name = "CELLHIVE_DO_SRC", text = embed "cellhive-do.js"),
        (name = "GATE_URL", text = "{{.GateURL}}"),
        (name = "OUTBOUND", service = "public-network"),
        (name = "PLATFORM", service = "private-outbound"),
        (name = "CH_DO_CONNECT", service = "cap-ws"),
        (name = "BINDINGS_WRAPPER_SRC", text = embed "bindings-wrapper.js"),
        (name = "FACADES_SRC", text = embed "facades.js"),
        (name = "LOG_TAIL_SRC", text = embed "log-tail.js"),
        (name = "RPC_CODEC_SRC", text = embed "rpc-codec.js"),
        (name = "LOG_TOKEN", text = "{{.LogToken}}"),
        (name = "DO_TICKET_SECRET", text = "{{.DoTicketSecret}}"),
        (name = "DO_LEASE_S", text = "{{.DoLeaseS}}"),
        (name = "DO_OBJECT_INDEX", text = "{{if .DOObjectIndex}}1{{end}}"),
        (name = "AI_URL", text = "{{.AIURL}}"),
        (name = "AI_KEY", text = "{{.AIKey}}"),
      ],
      globalOutbound = "private-outbound",
      durableObjectNamespaces = [
        (className = "Host", uniqueKey = "cellhive-do-host", enableSql = true{{if .PreventEviction}}, preventEviction = true{{end}}),
      ],
      durableObjectStorage = (localDisk = "do-disk"),
    )),

    (name = "do-disk", disk = (path = "{{.DiskDir}}", writable = true)),
    (name = "public-network", network = ( allow = [{{.OutboundAllowList}}] )),
    (name = "private-outbound", network = ( allow = ["public", "private"] )),
    (name = "cap-ws", network = ( allow = [{{.WsAllowList}}] )),
  ],
  sockets = [ (name = "do", address = "{{.Addr}}", http = (), service = "do" ) ],
);
`

// Render copies the platform JS into dir and writes the workerd config.
func Render(dir string, cfg Config) (string, error) {
	if cfg.Addr == "" || cfg.DiskDir == "" || cfg.PlatformJS == "" {
		return "", errors.New("doruntime: Addr, DiskDir and PlatformJS are required")
	}
	for _, a := range cfg.OutboundAllow {
		if !outboundCategories[strings.TrimSpace(a)] {
			return "", fmt.Errorf("doruntime: unknown outbound category %q (want public|private|local)", a)
		}
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	if err := os.MkdirAll(cfg.DiskDir, 0o755); err != nil {
		return "", err
	}
	for _, f := range []string{"host.js", "cellhive-do.js"} {
		data, err := os.ReadFile(filepath.Join(cfg.PlatformJS, f))
		if err != nil {
			return "", err
		}
		if err := os.WriteFile(filepath.Join(dir, f), data, 0o644); err != nil {
			return "", err
		}
	}
	// facades.js is still needed for the queue/scheduled wrapper path; bindings.js
	// provides the RPC capability entrypoints (ADR-090).
	for _, pair := range [][2]string{
		{filepath.Join(cfg.PlatformJS, "..", "platform", "facades.js"), "facades.js"},
		{filepath.Join(cfg.PlatformJS, "..", "platform", "bindings.js"), "bindings.js"},
		{filepath.Join(cfg.PlatformJS, "..", "platform", "bindings-wrapper.js"), "bindings-wrapper.js"},
		{filepath.Join(cfg.PlatformJS, "..", "platform", "log-tail.js"), "log-tail.js"},
		{filepath.Join(cfg.PlatformJS, "..", "platform", "rpc-codec.js"), "rpc-codec.js"},
		{filepath.Join(cfg.PlatformJS, "..", "platform", "telemetry.js"), "telemetry.js"},
	} {
		data, err := os.ReadFile(pair[0])
		if err != nil {
			return "", err
		}
		if err := os.WriteFile(filepath.Join(dir, pair[1]), data, 0o644); err != nil {
			return "", err
		}
	}
	tpl, err := template.New("capnp").Parse(capnpTemplate)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, cfg); err != nil {
		return "", err
	}
	path := filepath.Join(dir, "do-runtime.capnp")
	if err := os.WriteFile(path, buf.Bytes(), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// Run starts workerd with the rendered config and blocks until it exits or ctx is
// cancelled.
func Run(ctx context.Context, workerdBin, capnpPath string) error {
	cmd := exec.CommandContext(ctx, workerdBin, "serve", "--experimental", capnpPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// FindWorkerd locates the workerd binary (shared locator).
func FindWorkerd() (string, error) { return workerdbin.Find() }
