// Command workerd-compat-gen derives CellHive's compatibility authority from
// an explicit, local checkout of the exact upstream workerd revision. It never
// fetches the network.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const (
	compatibilitySource = "src/workerd/io/compatibility-date.capnp"
	maximumDateSource   = "src/workerd/io/maximum-compatibility-date.txt"
)

type manifestData struct {
	WorkerdVersion       string         `json:"workerd_version"`
	UpstreamRevision     string         `json:"upstream_revision"`
	SourceSHA256         string         `json:"source_sha256"`
	MaxCompatibilityDate string         `json:"max_compatibility_date"`
	Flags                []manifestFlag `json:"flags"`
}

type manifestFlag struct {
	Name            string `json:"name"`
	Experimental    bool   `json:"experimental"`
	CellHiveAllowed bool   `json:"cellhive_allowed"`
}

func main() {
	var source, version, revision, out, tsOut string
	flag.StringVar(&source, "source", "", "path to the exact upstream workerd checkout")
	flag.StringVar(&version, "version", "", "exact npm workerd version")
	flag.StringVar(&revision, "revision", "", "exact upstream Git revision")
	flag.StringVar(&out, "out", "", "manifest JSON output path")
	flag.StringVar(&tsOut, "ts-out", "", "optional generated TypeScript output path")
	flag.Parse()
	if err := generate(source, version, revision, out, tsOut); err != nil {
		fmt.Fprintln(os.Stderr, "workerd-compat-gen:", err)
		os.Exit(1)
	}
}

func generate(source, version, revision, out, tsOut string) error {
	if source == "" || version == "" || revision == "" || out == "" {
		return errors.New("-source, -version, -revision and -out are required")
	}
	compatPath := filepath.Join(source, compatibilitySource)
	compat, err := os.ReadFile(compatPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", compatPath, err)
	}
	maxPath := filepath.Join(source, maximumDateSource)
	maxRaw, err := os.ReadFile(maxPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", maxPath, err)
	}
	maxDate := strings.TrimSpace(string(maxRaw))
	if !regexp.MustCompile(`^\d{4}-\d{2}-\d{2}$`).MatchString(maxDate) {
		return fmt.Errorf("invalid maximum compatibility date %q", maxDate)
	}
	flags, err := parseCompatibilityFlags(compat)
	if err != nil {
		return err
	}
	digest := sha256.Sum256(compat)
	data := manifestData{
		WorkerdVersion: version, UpstreamRevision: revision,
		SourceSHA256:         hex.EncodeToString(digest[:]),
		MaxCompatibilityDate: maxDate, Flags: flags,
	}
	encoded, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return err
	}
	encoded = append(encoded, '\n')
	if err := os.WriteFile(out, encoded, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", out, err)
	}
	if tsOut != "" {
		if err := os.WriteFile(tsOut, renderTypeScript(data), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", tsOut, err)
		}
	}
	return nil
}

var (
	compatStructRE = regexp.MustCompile(`(?ms)^struct CompatibilityFlags[^\{]*\{(.*?)^\}`)
	fieldRE        = regexp.MustCompile(`(?ms)^\s*[A-Za-z][A-Za-z0-9_]*\s+@\d+\s+:[^;]+;`)
	flagRE         = regexp.MustCompile(`\$compat(?:Enable|Disable)Flag\("([^"]+)"\)`)
)

// explicitlyUnsupported covers upstream exceptions not represented by the
// $experimental annotation. Keep this list minimal and let the real-binary
// probe prove every remaining allowed flag starts without --experimental.
var explicitlyUnsupported = map[string]string{
	"new_module_registry": "stock workerd server requires --experimental",
}

func parseCompatibilityFlags(source []byte) ([]manifestFlag, error) {
	match := compatStructRE.FindSubmatch(source)
	if match == nil {
		return nil, errors.New("CompatibilityFlags struct not found")
	}
	byName := map[string]bool{}
	for _, field := range fieldRE.FindAll(match[1], -1) {
		experimental := bytes.Contains(field, []byte("$experimental"))
		for _, flag := range flagRE.FindAllSubmatch(field, -1) {
			name := string(flag[1])
			// If an upstream name ever appears in multiple fields, fail closed
			// when any occurrence is experimental.
			byName[name] = byName[name] || experimental
		}
	}
	if len(byName) == 0 {
		return nil, errors.New("no compatibility flags found")
	}
	flags := make([]manifestFlag, 0, len(byName))
	for name, experimental := range byName {
		_, unsupported := explicitlyUnsupported[name]
		flags = append(flags, manifestFlag{
			Name: name, Experimental: experimental, CellHiveAllowed: !experimental && !unsupported,
		})
	}
	sort.Slice(flags, func(i, j int) bool { return flags[i].Name < flags[j].Name })
	return flags, nil
}

func renderTypeScript(data manifestData) []byte {
	var out strings.Builder
	out.WriteString("// Code generated by cmd/workerd-compat-gen; DO NOT EDIT.\n")
	fmt.Fprintf(&out, "export const PINNED_WORKERD = %q as const;\n", data.WorkerdVersion)
	fmt.Fprintf(&out, "export const COMPAT_DATE_MAX = %q as const;\n", data.MaxCompatibilityDate)
	out.WriteString("export const KNOWN_COMPAT_FLAGS = new Set<string>([\n")
	flags := append([]manifestFlag(nil), data.Flags...)
	sort.Slice(flags, func(i, j int) bool { return flags[i].Name < flags[j].Name })
	for _, f := range flags {
		if f.CellHiveAllowed {
			fmt.Fprintf(&out, "  %q,\n", f.Name)
		}
	}
	out.WriteString("]);\n")
	return []byte(out.String())
}
