package cell

import "testing"

// Vectors generated by the do-runtime host's JS fnv1a (must match exactly).
func TestDOShardMatchesJS(t *testing.T) {
	cases := []struct {
		ns, worker, class, id string
		want                  int
	}{
		{"demo", "counter", "Tenant", "a1", 13},
		{"acme", "web", "Room", "x", 3},
		{"demo", "counter", "Tenant", "b2", 11},
	}
	for _, c := range cases {
		if got := DOShard(c.ns, c.worker, c.class, c.id); got != c.want {
			t.Fatalf("DOShard(%s/%s/%s/%s) = %d, want %d", c.ns, c.worker, c.class, c.id, got, c.want)
		}
	}
}
