// Package userruntime renders and launches the user-runtime workerd process
// (docs/architecture.md): a public loader (:8081) plus an internal privileged
// dispatch service (:8088) that runs tenant non-fetch handlers (queue/scheduled)
// by loading their immutable bundle through workerLoader.
//
// Host-only bindings are supplied through Cap'n Proto fromEnvironment entries;
// tenant bindings remain entirely user-owned.
package userruntime

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"text/template"

	"cellhive/internal/runtimeenv"
	"cellhive/internal/workerdbin"
)

// outboundCategories are the workerd network categories a tenant outbound policy
// may name.
var outboundCategories = map[string]bool{"public": true, "private": true, "local": true}

// renderedEnvs preserves compatibility for same-process Render/Run integration
// tests. Production launchers always pass WorkerdEnv explicitly; this map is
// never a parent-environment fallback and cannot cross a process boundary.
var renderedEnvs sync.Map

// OutboundAllowList renders the tenant outbound policy for the capnp config.
// Empty defaults to "public" (I-09, ADR-130).
func (c Config) OutboundAllowList() string {
	if len(c.OutboundAllow) == 0 {
		return `"public"`
	}
	parts := make([]string, 0, len(c.OutboundAllow))
	for _, a := range c.OutboundAllow {
		parts = append(parts, strconv.Quote(strings.TrimSpace(a)))
	}
	return strings.Join(parts, ", ")
}

// EgressAllowList renders the capability-data-plane egress policy for the
// loader worker's PLATFORM binding (cap-egress network). Entries are CIDR
// blocks or workerd categories naming the addresses runtime-services resolves
// to (e.g. "10.20.0.0/16" for the capability data-plane subnet); "public" is always
// included so a cross-network runtime-services endpoint (public domain) also
// works. Empty defaults to the legacy permissive posture (public+private) so
// existing deployments and dev keep working until EgressAllow is configured.
func (c Config) EgressAllowList() string {
	parts := make([]string, 0, len(c.EgressAllow)+1)
	parts = append(parts, `"public"`)
	for _, a := range c.EgressAllow {
		if a = strings.TrimSpace(a); a != "" {
			parts = append(parts, strconv.Quote(a))
		}
	}
	if len(parts) == 1 {
		// No EgressAllow configured: keep the old permissive behavior.
		parts = append(parts, `"private"`)
	}
	return strings.Join(parts, ", ")
}

// Config is the runtime configuration for one user-runtime instance.
type Config struct {
	CellURL      string
	CellToken    string
	InternalPort int
	PublicPort   int
	// PlatformJS is the directory holding internal.js, queue-wrapper.js, loader.js.
	PlatformJS string
	// FacadesJS is the path to facades.js (binding facades injected into tenants).
	FacadesJS string
	// ScopeSecret is the HMAC key the loader uses to compute binding tokens
	// locally (ADR-074). Must match the cell-agent's scope secret.
	ScopeSecret string
	// DispatchToken guards the internal dispatch endpoints (ADR-075).
	DispatchToken string
	// AIURL/AIKey configure the BYO OpenAI-compatible AI binding endpoint.
	AIURL string
	AIKey string
	// ServiceNative ("0" disables) selects the same-instance native service
	// binding path (ADR-102); empty = enabled.
	ServiceNative string
	// DoDirect ("0" disables) selects the DO caller-side owner-hint direct call
	// (ADR-105); empty = enabled.
	DoDirect string
	// TraceSampleRatio is the head sampling ratio for generated traceparents
	// (ADR-167); 0 disables recording of new traces (upstream flags still win).
	TraceSampleRatio float64
	// HostCacheTTLMs overrides the loader's per-host routing cache TTL (ADR-115);
	// 0 = the 10s default. Tests set a short TTL.
	HostCacheTTLMs int
	// RevPollMs overrides the routing revision poll interval (ADR-116); 0 = 2s.
	RevPollMs int
	// HostLookupMaxPerSec caps upstream lookups for unknown hosts (ADR-116);
	// 0 = 100.
	HostLookupMaxPerSec int
	// OutboundAllow is the tenant workers' outbound network policy (ADR-130).
	// Empty = ["public"] (I-09). Adding "private"/"local" lets tenants reach
	// private-network origins (e.g. a DB) at the cost of the public-only floor.
	OutboundAllow []string
	// EgressAllow names extra network ranges the loader worker's PLATFORM
	// binding (cap-egress) may reach, on top of the fixed public+private
	// fallback. The PLATFORM binding is cellhive's internal transport for its
	// own binding facades (cell-agent :7001) — narrowing it breaks every
	// facade call (verified by userruntime e2e), so it is deployment plumbing
	// rather than a tenant-facing security knob: private-network safety rests
	// on role credentials (ADR-074), never on this allowlist.
	EgressAllow []string
}

const capnpTemplate = `# Generated by user-runtime; do not edit.
using Workerd = import "/workerd/workerd.capnp";

const config :Workerd.Config = (
  services = [
    (name = "internal", worker = (
      modules = [
        (name = "internal.js", esModule = embed "internal.js"),
        (name = "bindings.js", esModule = embed "bindings.js"),
        (name = "rpc-codec.js", esModule = embed "rpc-codec.js"),
        (name = "facades.js", esModule = embed "facades.js"),
        (name = "telemetry.js", esModule = embed "telemetry.js"),
      ],
      compatibilityDate = "2026-06-15",
      bindings = [
        (name = "LOADER", workerLoader = (id = "cellhive-user-runtime")),
        (name = "CELL_URL", fromEnvironment = "CELLHIVE_HOST_CELL_URL"),
        (name = "CELL_TOKEN", fromEnvironment = "CELLHIVE_HOST_CELL_TOKEN"),
        (name = "DISPATCH_TOKEN", fromEnvironment = "CELLHIVE_HOST_DISPATCH_TOKEN"),
        (name = "WRAPPER_SRC", text = embed "queue-wrapper.js"),
        (name = "WF_WRAPPER_SRC", text = embed "workflow-wrapper.js"),
        (name = "WF_BASE_SRC", text = embed "cellhive-workflow.js"),
        (name = "FACADES_SRC", text = embed "facades.js"),
        (name = "RPC_CODEC_SRC", text = embed "rpc-codec.js"),
        (name = "AI_URL", fromEnvironment = "CELLHIVE_HOST_AI_URL"),
        (name = "AI_KEY", fromEnvironment = "CELLHIVE_HOST_AI_KEY"),
        (name = "OUTBOUND", service = "public-network"),
        (name = "PLATFORM", service = "private-outbound"),
        (name = "CH_SERVICE_NATIVE", text = "{{.ServiceNative}}"),
        (name = "CH_DO_DIRECT", text = "{{.DoDirect}}"),
      ],
      globalOutbound = "private-outbound",
    )),

    (name = "loader", worker = (
      modules = [
        (name = "loader.js", esModule = embed "loader.js"),
        (name = "bindings.js", esModule = embed "bindings.js"),
        (name = "rpc-codec.js", esModule = embed "rpc-codec.js"),
        (name = "facades.js", esModule = embed "facades.js"),
        (name = "telemetry.js", esModule = embed "telemetry.js"),
      ],
      compatibilityDate = "2026-06-15",
      bindings = [
        (name = "LOADER", workerLoader = (id = "cellhive-user-runtime-loader")),
        (name = "CELL_URL", fromEnvironment = "CELLHIVE_HOST_CELL_URL"),
        (name = "CELL_TOKEN", fromEnvironment = "CELLHIVE_HOST_CELL_TOKEN"),
        (name = "SCOPE_SECRET", fromEnvironment = "CELLHIVE_HOST_SCOPE_SECRET"),
        (name = "WRAPPER_SRC", text = embed "queue-wrapper.js"),
        (name = "WF_WRAPPER_SRC", text = embed "workflow-wrapper.js"),
        (name = "WF_BASE_SRC", text = embed "cellhive-workflow.js"),
        (name = "FACADES_SRC", text = embed "facades.js"),
        (name = "RPC_CODEC_SRC", text = embed "rpc-codec.js"),
        (name = "AI_URL", fromEnvironment = "CELLHIVE_HOST_AI_URL"),
        (name = "AI_KEY", fromEnvironment = "CELLHIVE_HOST_AI_KEY"),
        (name = "OUTBOUND", service = "public-network"),
        (name = "PLATFORM", service = "cap-egress"),
        (name = "CH_SERVICE_NATIVE", text = "{{.ServiceNative}}"),
        (name = "CH_DO_DIRECT", text = "{{.DoDirect}}"),
        (name = "CH_TRACE_RATIO", text = "{{.TraceSampleRatio}}"),
        (name = "HOST_TTL_MS", text = "{{.HostCacheTTLMs}}"),
        (name = "REV_POLL_MS", text = "{{.RevPollMs}}"),
        (name = "HOST_LOOKUP_MAX_PER_SEC", text = "{{.HostLookupMaxPerSec}}"),
      ],
      globalOutbound = "private-outbound",
    )),

    (name = "public-network", network = ( allow = [{{.OutboundAllowList}}] )),
    (name = "private-outbound", network = ( allow = ["public", "private"] )),
    (name = "cap-egress", network = ( allow = [{{.EgressAllowList}}] )),
  ],
  sockets = [
    (name = "internal", address = "*:{{.InternalPort}}", http = (), service = "internal" ),
    (name = "public", address = "*:{{.PublicPort}}", http = (), service = "loader" ),
  ],
);
`

// Render copies the platform JS into dir and writes the workerd config, returning
// its path.
func Render(dir string, cfg Config) (string, error) {
	if cfg.CellURL == "" || cfg.InternalPort == 0 || cfg.PublicPort == 0 {
		return "", errors.New("userruntime: CellURL, InternalPort and PublicPort are required")
	}
	if cfg.PlatformJS == "" || cfg.FacadesJS == "" {
		return "", errors.New("userruntime: PlatformJS and FacadesJS are required")
	}
	childEnv, err := WorkerdEnv(cfg)
	if err != nil {
		return "", err
	}
	for _, a := range cfg.OutboundAllow {
		if !outboundCategories[strings.TrimSpace(a)] {
			return "", fmt.Errorf("userruntime: unknown outbound category %q (want public|private|local)", a)
		}
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	for _, f := range []string{"internal.js", "queue-wrapper.js", "workflow-wrapper.js", "cellhive-workflow.js", "loader.js"} {
		if err := copyFile(filepath.Join(cfg.PlatformJS, f), filepath.Join(dir, f)); err != nil {
			return "", err
		}
	}
	if err := copyFile(cfg.FacadesJS, filepath.Join(dir, "facades.js")); err != nil {
		return "", err
	}
	if err := copyFile(filepath.Join(cfg.PlatformJS, "..", "platform", "rpc-codec.js"), filepath.Join(dir, "rpc-codec.js")); err != nil {
		return "", err
	}
	if err := copyFile(filepath.Join(cfg.PlatformJS, "..", "platform", "bindings.js"), filepath.Join(dir, "bindings.js")); err != nil {
		return "", err
	}
	if err := copyFile(filepath.Join(cfg.PlatformJS, "..", "platform", "telemetry.js"), filepath.Join(dir, "telemetry.js")); err != nil {
		return "", err
	}
	tpl, err := template.New("capnp").Parse(capnpTemplate)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, cfg); err != nil {
		return "", err
	}
	path := filepath.Join(dir, "user-runtime.capnp")
	if err := os.WriteFile(path, buf.Bytes(), 0o644); err != nil {
		return "", err
	}
	renderedEnvs.Store(path, childEnv)
	return path, nil
}

// WorkerdEnv returns the complete host environment consumed by the generated
// Cap'n Proto fromEnvironment bindings.
func WorkerdEnv(cfg Config) ([]string, error) {
	return runtimeenv.Build(map[string]string{
		"CELLHIVE_HOST_AI_KEY":         cfg.AIKey,
		"CELLHIVE_HOST_AI_URL":         cfg.AIURL,
		"CELLHIVE_HOST_CELL_TOKEN":     cfg.CellToken,
		"CELLHIVE_HOST_CELL_URL":       cfg.CellURL,
		"CELLHIVE_HOST_DISPATCH_TOKEN": cfg.DispatchToken,
		"CELLHIVE_HOST_SCOPE_SECRET":   cfg.ScopeSecret,
	})
}

// Run starts workerd with the rendered config and blocks until it exits or ctx is
// cancelled. workerd stderr/stdout are inherited.
func Run(ctx context.Context, workerdBin, capnpPath string, supplied ...[]string) error {
	var childEnv []string
	if len(supplied) > 1 {
		return errors.New("userruntime: Run accepts at most one child environment")
	}
	if len(supplied) == 1 {
		childEnv = supplied[0]
		renderedEnvs.Delete(capnpPath)
	} else if saved, ok := renderedEnvs.LoadAndDelete(capnpPath); ok {
		childEnv = saved.([]string)
	}
	if err := runtimeenv.Require(childEnv,
		"CELLHIVE_HOST_AI_KEY",
		"CELLHIVE_HOST_AI_URL",
		"CELLHIVE_HOST_CELL_TOKEN",
		"CELLHIVE_HOST_CELL_URL",
		"CELLHIVE_HOST_DISPATCH_TOKEN",
		"CELLHIVE_HOST_SCOPE_SECRET",
	); err != nil {
		return fmt.Errorf("userruntime: child environment: %w", err)
	}
	cmd := exec.CommandContext(ctx, workerdBin, "serve", "--experimental", capnpPath)
	// A nil Cmd.Env inherits the parent. Allocate even for an explicitly empty
	// environment so no system-reserved variables reach workerd.
	cmd.Env = append(make([]string, 0, len(childEnv)), childEnv...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// FindWorkerd locates the workerd binary (shared locator).
func FindWorkerd() (string, error) { return workerdbin.Find() }

func copyFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return fmt.Errorf("userruntime: read %s: %w", src, err)
	}
	return os.WriteFile(dst, data, 0o644)
}
