// Package userruntime renders and launches the user-runtime workerd process
// (docs/architecture.md): a public loader (:8081) plus an internal privileged
// dispatch service (:8088) that runs tenant non-fetch handlers (queue/scheduled)
// by loading their immutable bundle through workerLoader.
//
// workerd cannot read environment variables into bindings, so the Cap'n Proto
// config is rendered at startup from a template with the cell-agent URL/token and
// ports substituted in.
package userruntime

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"

	"cellhive/internal/workerdbin"
)

// outboundCategories are the workerd network categories a tenant outbound policy
// may name.
var outboundCategories = map[string]bool{"public": true, "private": true, "local": true}

// OutboundAllowList renders the tenant outbound policy for the capnp config.
// Empty defaults to "public" (I-09, ADR-130).
func (c Config) OutboundAllowList() string {
	if len(c.OutboundAllow) == 0 {
		return `"public"`
	}
	parts := make([]string, 0, len(c.OutboundAllow))
	for _, a := range c.OutboundAllow {
		parts = append(parts, strconv.Quote(strings.TrimSpace(a)))
	}
	return strings.Join(parts, ", ")
}

// Config is the runtime configuration for one user-runtime instance.
type Config struct {
	CellURL      string
	CellToken    string
	InternalPort int
	PublicPort   int
	// PlatformJS is the directory holding internal.js, queue-wrapper.js, loader.js.
	PlatformJS string
	// FacadesJS is the path to facades.js (binding facades injected into tenants).
	FacadesJS string
	// ScopeSecret is the HMAC key the loader uses to compute binding tokens
	// locally (ADR-074). Must match the cell-agent's scope secret.
	ScopeSecret string
	// DispatchToken guards the internal dispatch endpoints (ADR-075).
	DispatchToken string
	// AIURL/AIKey configure the BYO OpenAI-compatible AI binding endpoint.
	AIURL string
	AIKey string
	// LogToken authorizes the bounded log-ingest endpoint (loaded workers).
	LogToken string
	// ServiceNative ("0" disables) selects the same-instance native service
	// binding path (ADR-102); empty = enabled.
	ServiceNative string
	// DoDirect ("0" disables) selects the DO caller-side owner-hint direct call
	// (ADR-105); empty = enabled.
	DoDirect string
	// TraceSampleRatio is the head sampling ratio for generated traceparents
	// (ADR-167); 0 disables recording of new traces (upstream flags still win).
	TraceSampleRatio float64
	// HostCacheTTLMs overrides the loader's per-host routing cache TTL (ADR-115);
	// 0 = the 10s default. Tests set a short TTL.
	HostCacheTTLMs int
	// RevPollMs overrides the routing revision poll interval (ADR-116); 0 = 2s.
	RevPollMs int
	// HostLookupMaxPerSec caps upstream lookups for unknown hosts (ADR-116);
	// 0 = 100.
	HostLookupMaxPerSec int
	// OutboundAllow is the tenant workers' outbound network policy (ADR-130).
	// Empty = ["public"] (I-09). Adding "private"/"local" lets tenants reach
	// private-network origins (e.g. a DB) at the cost of the public-only floor.
	OutboundAllow []string
}

const capnpTemplate = `# Generated by user-runtime; do not edit.
using Workerd = import "/workerd/workerd.capnp";

const config :Workerd.Config = (
  services = [
    (name = "internal", worker = (
      modules = [
        (name = "internal.js", esModule = embed "internal.js"),
        (name = "bindings.js", esModule = embed "bindings.js"),
        (name = "telemetry.js", esModule = embed "telemetry.js"),
      ],
      compatibilityDate = "2026-06-15",
      bindings = [
        (name = "LOADER", workerLoader = (id = "cellhive-user-runtime")),
        (name = "CELL_URL", text = "{{.CellURL}}"),
        (name = "CELL_TOKEN", text = "{{.CellToken}}"),
        (name = "DISPATCH_TOKEN", text = "{{.DispatchToken}}"),
        (name = "WRAPPER_SRC", text = embed "queue-wrapper.js"),
        (name = "WF_WRAPPER_SRC", text = embed "workflow-wrapper.js"),
        (name = "WF_BASE_SRC", text = embed "cellhive-workflow.js"),
        (name = "FACADES_SRC", text = embed "facades.js"),
        (name = "RPC_CODEC_SRC", text = embed "rpc-codec.js"),
        (name = "LOG_TAIL_SRC", text = embed "log-tail.js"),
        (name = "LOG_TOKEN", text = "{{.LogToken}}"),
        (name = "AI_URL", text = "{{.AIURL}}"),
        (name = "AI_KEY", text = "{{.AIKey}}"),
        (name = "OUTBOUND", service = "public-network"),
        (name = "PLATFORM", service = "private-outbound"),
        (name = "CH_SERVICE_NATIVE", text = "{{.ServiceNative}}"),
        (name = "CH_DO_DIRECT", text = "{{.DoDirect}}"),
      ],
      globalOutbound = "private-outbound",
    )),

    (name = "loader", worker = (
      modules = [
        (name = "loader.js", esModule = embed "loader.js"),
        (name = "bindings.js", esModule = embed "bindings.js"),
        (name = "telemetry.js", esModule = embed "telemetry.js"),
      ],
      compatibilityDate = "2026-06-15",
      bindings = [
        (name = "LOADER", workerLoader = (id = "cellhive-user-runtime-loader")),
        (name = "CELL_URL", text = "{{.CellURL}}"),
        (name = "CELL_TOKEN", text = "{{.CellToken}}"),
        (name = "SCOPE_SECRET", text = "{{.ScopeSecret}}"),
        (name = "WRAPPER_SRC", text = embed "queue-wrapper.js"),
        (name = "WF_WRAPPER_SRC", text = embed "workflow-wrapper.js"),
        (name = "WF_BASE_SRC", text = embed "cellhive-workflow.js"),
        (name = "FACADES_SRC", text = embed "facades.js"),
        (name = "RPC_CODEC_SRC", text = embed "rpc-codec.js"),
        (name = "LOG_TAIL_SRC", text = embed "log-tail.js"),
        (name = "LOG_TOKEN", text = "{{.LogToken}}"),
        (name = "AI_URL", text = "{{.AIURL}}"),
        (name = "AI_KEY", text = "{{.AIKey}}"),
        (name = "OUTBOUND", service = "public-network"),
        (name = "PLATFORM", service = "private-outbound"),
        (name = "CH_SERVICE_NATIVE", text = "{{.ServiceNative}}"),
        (name = "CH_DO_DIRECT", text = "{{.DoDirect}}"),
        (name = "CH_TRACE_RATIO", text = "{{.TraceSampleRatio}}"),
        (name = "HOST_TTL_MS", text = "{{.HostCacheTTLMs}}"),
        (name = "REV_POLL_MS", text = "{{.RevPollMs}}"),
        (name = "HOST_LOOKUP_MAX_PER_SEC", text = "{{.HostLookupMaxPerSec}}"),
      ],
      globalOutbound = "private-outbound",
    )),

    (name = "public-network", network = ( allow = [{{.OutboundAllowList}}] )),
    (name = "private-outbound", network = ( allow = ["public", "private"] )),
  ],
  sockets = [
    (name = "internal", address = "*:{{.InternalPort}}", http = (), service = "internal" ),
    (name = "public", address = "*:{{.PublicPort}}", http = (), service = "loader" ),
  ],
);
`

// Render copies the platform JS into dir and writes the workerd config, returning
// its path.
func Render(dir string, cfg Config) (string, error) {
	if cfg.CellURL == "" || cfg.InternalPort == 0 || cfg.PublicPort == 0 {
		return "", errors.New("userruntime: CellURL, InternalPort and PublicPort are required")
	}
	if cfg.PlatformJS == "" || cfg.FacadesJS == "" {
		return "", errors.New("userruntime: PlatformJS and FacadesJS are required")
	}
	for _, a := range cfg.OutboundAllow {
		if !outboundCategories[strings.TrimSpace(a)] {
			return "", fmt.Errorf("userruntime: unknown outbound category %q (want public|private|local)", a)
		}
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	for _, f := range []string{"internal.js", "queue-wrapper.js", "workflow-wrapper.js", "cellhive-workflow.js", "loader.js"} {
		if err := copyFile(filepath.Join(cfg.PlatformJS, f), filepath.Join(dir, f)); err != nil {
			return "", err
		}
	}
	if err := copyFile(cfg.FacadesJS, filepath.Join(dir, "facades.js")); err != nil {
		return "", err
	}
	if err := copyFile(filepath.Join(cfg.PlatformJS, "..", "platform", "rpc-codec.js"), filepath.Join(dir, "rpc-codec.js")); err != nil {
		return "", err
	}
	if err := copyFile(filepath.Join(cfg.PlatformJS, "..", "platform", "bindings.js"), filepath.Join(dir, "bindings.js")); err != nil {
		return "", err
	}
	if err := copyFile(filepath.Join(cfg.PlatformJS, "..", "platform", "log-tail.js"), filepath.Join(dir, "log-tail.js")); err != nil {
		return "", err
	}
	if err := copyFile(filepath.Join(cfg.PlatformJS, "..", "platform", "telemetry.js"), filepath.Join(dir, "telemetry.js")); err != nil {
		return "", err
	}
	tpl, err := template.New("capnp").Parse(capnpTemplate)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, cfg); err != nil {
		return "", err
	}
	path := filepath.Join(dir, "user-runtime.capnp")
	if err := os.WriteFile(path, buf.Bytes(), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// Run starts workerd with the rendered config and blocks until it exits or ctx is
// cancelled. workerd stderr/stdout are inherited.
func Run(ctx context.Context, workerdBin, capnpPath string) error {
	cmd := exec.CommandContext(ctx, workerdBin, "serve", "--experimental", capnpPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// FindWorkerd locates the workerd binary (shared locator).
func FindWorkerd() (string, error) { return workerdbin.Find() }

func copyFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return fmt.Errorf("userruntime: read %s: %w", src, err)
	}
	return os.WriteFile(dst, data, 0o644)
}
